### ISSUE TITLE
Parentheses/Bracket/Braces pair height looks slightly off at certain font sizes

### ISSUE THREAD

**Issue by krish-r** [arrowtype/recursive#297] opened 2020-01-16 09:37 UTC
Hello, 

Parentheses/Bracket/Braces pair height looks slightly off at certain font sizes.

| | |
| --- | --- |
| OS | Windows 10 |
| VS Code version | 1.41.1 |
| Font version | 1.030 |
| Font Style | Recursive Mono Csl b030st |
| Font Ligatures | Enabled (Only dlig) |

Attached samples from Casual version. (Could see the observation in Linear version as well).

References where heights look equal:
![image](https://user-images.githubusercontent.com/54745129/72510244-16025b80-386f-11ea-9e07-ba6f62808ad3.png)

![image](https://user-images.githubusercontent.com/54745129/72510312-3a5e3800-386f-11ea-944a-795e571677a5.png)

Observations where the pair looks slightly-off: 
![image](https://user-images.githubusercontent.com/54745129/72510370-5530ac80-386f-11ea-8702-1c5c31fd65ae.png)

![image](https://user-images.githubusercontent.com/54745129/72510276-274b6800-386f-11ea-8cab-5809a34a39f5.png)

Thanks! :)

**Comment by kamenminkov** [comment] 2020-01-21 08:35
Can confirm, it's the same for me in latest stable VSCode on Windows 10 2004 (19546). Seems dependent on font weight too - i.e. at a given size, some weights look okay (regarding brackets/braces/parenthesis), others - not.

**Comment by arrowtype** [comment] 2020-01-23 06:08
Thanks, @krish-r & @kamenminkov! Good eyes on this.

What OS are you on?

Can you please try the static fonts in v1.034, and let me know whether you still have the same issue?

https://github.com/arrowtype/recursive/tree/e882954365d4fafdf2fb43abeff99a28d615f32e/fonts_1.034

These should be activated like:

`RecursiveMonoLnr-Regular` and  `RecursiveMonoCsl-Regular`

(With no version number in the name, this time).

**Comment by krish-r** [comment] 2020-01-23 17:41
Hi @arrowtype , I was able to activate Recursive after specifying editor.fontFamily as 'Recursive Mono Casual'/'Recursive Mono Linear'

Unfortunately, I'm still seeing difference in the heights. 

![image](https://user-images.githubusercontent.com/54745129/73008419-88a5a500-3e34-11ea-9393-85e16fe001ba.png)

![image](https://user-images.githubusercontent.com/54745129/73008879-7710cd00-3e35-11ea-8ccd-576b5bd825c1.png)


![image](https://user-images.githubusercontent.com/54745129/73008617-ecc86900-3e34-11ea-8353-3e5cb567ff97.png)

![image](https://user-images.githubusercontent.com/54745129/73008669-0a95ce00-3e35-11ea-9480-e8cc9b3ee9f7.png)

**Comment by thundernixon** [comment] 2020-01-23 17:46
Okay, thanks for trying that out! I’ll take a closer look and give it a try on Windows. 

My guess is, the right brackets are using components of left brackets, and Windows is either pixel-aliasing those a bit differently because they are components, or because perhaps they are just aligned slightly lower and the difference is being magnified. 

I’ll update this when I know more, hopefully within the coming week or so.

**Comment by krish-r** [comment] 2020-01-23 17:55
Thanks @thundernixon .

And, I'm sorry, this completely unrelated question, was there any change to how the "tittle" looks on lowercase "i"? Because I could see that it's slightly different between my original & current screenshots - Size 17, for ex..

PS. Happy to (re)move this comment if you feel this is hijacking the issue.

**Comment by thundernixon** [comment] 2020-01-23 17:57
We have added an autohinting step to the static build process, which should hopefully, mostly help with rendering in Windows, but may have some trade offs. That’s also why I thought the brackets might be different, though. I’ll also take a look at the i dot and diacritics in general. Thanks!

**Comment by jkyeung** [comment] 2020-07-25 09:02
Just wanted to mention I'm still seeing this at v1.052 on Windows, using VS Code.

**Comment by arrowtype** [comment] 2020-11-13 04:38
Okay, finally trying to work through this. I am trying out adding a step into the build that decomposes opening/closing punctuation like these, and that may help.

Just as an extra note, I’ve noticed that parentheses are slightly shorter in the bolder Sans styles:

<details>
<summary><b>side issues</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/45946693/98999301-8fa5bd00-2505-11eb-8ce1-d824bef1f224.png)

...and the () and [] are shorter in the bolder Mono styles:

![image](https://user-images.githubusercontent.com/45946693/98999528-f4f9ae00-2505-11eb-8a82-a84598379b4c.png)

</details>

So, I’ll go through and make sure these are the same height.

Adjustments:

- [x] Making  `( ) [ ]` the same height as `{ }`
- [x ] Making sure the blue zones cover these
- [x] Making sure the `.case` versions are also aligned & matching heights

**Comment by arrowtype** [comment] 2020-11-13 04:40
I’ve rebuilt fonts with the fixes, and the new ones are here:

https://github.com/arrowtype/recursive/tree/4b59fd2f5ce78c342418c894d3a7e620819cac23/fonts_1.067

Would someone who has had this issue be willing to try these new fonts out on your system? @krish-r, @kamenminkov, @@jkyeung, or @jwortmann? I am hopefully it might work, but not totally certain. 🤞

**Comment by jwortmann** [comment] 2020-11-13 05:05
The parentheses/brackets/braces look perfect for me now 👍 , but there is still a misalignment between the "less than" and "greater than" symbols `<>` on all font sizes.

![font](https://user-images.githubusercontent.com/6579999/99030921-185c4180-2576-11eb-806b-109c639e3260.png)

Tested with `RecursiveMonoLnrSt-Regular.ttf` + italic & bold variants on Windows 10 v2004, Sublime Text 3.2.2.

**Comment by krish-r** [comment] 2020-11-13 10:21
Hello, 

Editor & OS: `VS Code v1.51.1, Windows 10 v20H2`

**_Static font_** 
As @jwortmann mentioned, I could see misalignment only with the angle bracket, rest of them looks perfect. 

`RecursiveMonoLnrSt-Regular.ttf` - angle bracket is misaligned for most of the font sizes
![image](https://user-images.githubusercontent.com/54745129/99060945-ce4f7c00-25c6-11eb-93c8-803fe8861086.png)
![image](https://user-images.githubusercontent.com/54745129/99059406-8fb8c200-25c4-11eb-8484-4f0c3e5ccba0.png)

`RecursiveMonoCslSt-Regular.ttf` - angle bracket is misaligned for size 16 & 17 (Matches for other sizes ex. 14)
![image](https://user-images.githubusercontent.com/54745129/99061064-ff2fb100-25c6-11eb-8b7e-94787fe226e8.png)
![image](https://user-images.githubusercontent.com/54745129/99059712-f342ef80-25c4-11eb-8bc1-0133e2538e67.png)

---

**_Variable font_**
And when I tried the variable font, everything (including angle bracket) aligns perfectly for me. 

`Recursive_VF_1.067.ttf`
![image](https://user-images.githubusercontent.com/54745129/99049556-ff2ab380-25bc-11eb-96e1-5ec2c08e606e.png)
![image](https://user-images.githubusercontent.com/54745129/99049646-19fd2800-25bd-11eb-89d5-843c149f4288.png)
![image](https://user-images.githubusercontent.com/54745129/99049475-e7532f80-25bc-11eb-81ef-027f8cf2081d.png)
![image](https://user-images.githubusercontent.com/54745129/99060050-7b28f980-25c5-11eb-86e4-353cd3981b74.png) (Linear)
![image](https://user-images.githubusercontent.com/54745129/99049728-339e6f80-25bd-11eb-8584-7df4b90c7dab.png)

**Comment by arrowtype** [comment] 2020-11-13 20:49
Hey @jwortmann & @krish-r, thanks so much for such quick tests & responses! 

I’m partially noting this down so I remember when I circle back to fix this soon, but...

My guess is, the height differences come from the angle brackets being vertically asymmetrical. They mimic brush strokes, which would tend to be asymmetrical. But, this means that even when they are visually vertically aligned, Windows rendering probably sees the difference in coordinate heights and snaps them to vertical pixels differently. This happens when hinting is present, which means that the static fonts (which have autohinting) show this, while the variable font (which doesn’t have hinting) doesn’t produce the difference. So, I should edit these to have shapes that are more symmetrical, somewhat similar to how I’ve treated arrows.

![image](https://user-images.githubusercontent.com/45946693/99119427-38682100-25c7-11eb-8888-3f1f06cde97a.png)

I will hopefully be able to get to this early next week. I’ll update this ASAP!

**Comment by krish-r** [comment] 2020-12-11 14:19
Hello @arrowtype, 

Thanks, Tried v1.068, the Angle brackets are now aligned properly. Unfortunately, I could see some slight misalignments in rest of the brackets.

Editor & OS: `VS Code v1.52.0, Windows 10 v20H2`

**Recursive_Code:** 
_Rec Mono Linear:_ 
![image](https://user-images.githubusercontent.com/54745129/101912494-d6abce80-3be7-11eb-9d18-9d4065e415d3.png)

![image](https://user-images.githubusercontent.com/54745129/101912272-8a608e80-3be7-11eb-93b1-96a4614c7388.png)

![image](https://user-images.githubusercontent.com/54745129/101912388-ad8b3e00-3be7-11eb-9e55-abc3c7ca601c.png)

![image](https://user-images.githubusercontent.com/54745129/101912411-b67c0f80-3be7-11eb-99f6-86f96fbec29c.png)

_Rec Mono Casual:_
![image](https://user-images.githubusercontent.com/54745129/101913009-76695c80-3be8-11eb-8857-975b3fa85ed4.png)

![image](https://user-images.githubusercontent.com/54745129/101913063-884aff80-3be8-11eb-84ee-160947a0ef1e.png)

![image](https://user-images.githubusercontent.com/54745129/101913084-8f720d80-3be8-11eb-95da-69c7e96fa8e7.png)

![image](https://user-images.githubusercontent.com/54745129/101913110-9731b200-3be8-11eb-837b-e1e0b7d57a5d.png)

**Comment by arrowtype** [comment] 2020-12-11 15:01
@krish-r thank you so much for helping test with this! Hmm, two things:

1. *facepalm* I had made the earlier fixes in a branch, then didn’t merge them into the main branch before working on new issues. Specifically, I had decomposed the closing punctuation, and (I think) adjusted vertical heights slightly. So, I’ll go bring those fixes in and make another new release as soon as possible.
2. It looks like you used the "Code" fonts, which have a new ligature for `<>` – so those are now just showing a single glyph, which may be throwing off the result. To get an accurate result, we’ll have to test that combo with a space between them.

I was over-confident here, thinking I had nailed it with the new release. 😅 Sorry! I’ll specifically test this in a Windows VM before making a new release and asking for confirmation.

**Comment by krish-r** [comment] 2020-12-11 16:57
Always happy to test! And yeah, you were correct, I forgot to turn-off the ligatures. 
Tried them with again with `"editor.fontLigatures": false`. 


_Rec Mono Linear:_
![image](https://user-images.githubusercontent.com/54745129/101931050-ef73ae80-3bfe-11eb-9ce5-55912c968902.png)

![image](https://user-images.githubusercontent.com/54745129/101931074-f6022600-3bfe-11eb-978f-a6035fcd4798.png)

![image](https://user-images.githubusercontent.com/54745129/101931100-fdc1ca80-3bfe-11eb-9a4a-89491fcaabac.png)

![image](https://user-images.githubusercontent.com/54745129/101931128-04e8d880-3bff-11eb-97c8-db4d36440200.png)


_Rec Mono Casual:_ 
![image](https://user-images.githubusercontent.com/54745129/101930750-9277f880-3bfe-11eb-8391-2eed6caefbd6.png)

![image](https://user-images.githubusercontent.com/54745129/101930886-be937980-3bfe-11eb-90ea-f76cb76e0c80.png)

![image](https://user-images.githubusercontent.com/54745129/101930920-c8b57800-3bfe-11eb-91a2-1f037c569477.png)

![image](https://user-images.githubusercontent.com/54745129/101930946-d0751c80-3bfe-11eb-97ea-06a265febb15.png)

**Comment by arrowtype** [comment] 2020-12-11 17:37
Nice! Yeah, as I was testing, I remembered that VS Code makes it easy to deactivate code ligatures. But thanks also for pointing that out here!

In my tests, the punctuation wasn’t _completely perfectly symmetrical,_ but seems to avoid the whole-pixel-off problem.

![image](https://user-images.githubusercontent.com/45946693/101935716-7ac45400-3bad-11eb-9a6c-1e9ee421ad22.png)

If you have time, @krish-r, could you try out the latest release, https://github.com/arrowtype/recursive/releases/tag/1.069? It adds the decomposition step that seemed to help in the earlier tests.

**Comment by krish-r** [comment] 2020-12-11 18:10
Tried v1.069. And, the brackets are looking aligned to me as well! 👌

Thanks @arrowtype! 

_Rec Mono Linear_
![image](https://user-images.githubusercontent.com/54745129/101937237-9a886600-3c07-11eb-9612-3f51c730cc90.png)
![image](https://user-images.githubusercontent.com/54745129/101937297-affd9000-3c07-11eb-8233-9891334d0f30.png)
![image](https://user-images.githubusercontent.com/54745129/101937320-b8ee6180-3c07-11eb-8723-1698c9d9ca10.png)
![image](https://user-images.githubusercontent.com/54745129/101937344-c0156f80-3c07-11eb-81ac-b50d1981e039.png)


_Rec Mono Casual_
![image](https://user-images.githubusercontent.com/54745129/101937405-d4596c80-3c07-11eb-8e1a-ddb0732ffd63.png)
![image](https://user-images.githubusercontent.com/54745129/101937442-e0452e80-3c07-11eb-9d21-66ab00c1b822.png)
![image](https://user-images.githubusercontent.com/54745129/101937485-eaffc380-3c07-11eb-86f8-1af1c408467e.png)
![image](https://user-images.githubusercontent.com/54745129/101937507-f3f09500-3c07-11eb-915a-42974d558c1a.png)

**Comment by arrowtype** [comment] 2020-12-11 18:22
Awesome, thank you so much for all your help in testing this out!

Happy we got this sorted.

**Closed** 2020-12-11 18:22 UTC
Labels: bug, details to fix, fixed in sources, priority 1

**Comment by jwortmann** [comment] 2020-12-11 22:58
I can confirm that with version 1.069 all types of brackets and the `<` and `>` symbols are aligned correctly for me as well. Thanks a lot for the update!

**Comment by arrowtype** [comment] 2020-12-16 20:37
Thanks for confirming, @jwortmann!
