### ISSUE TITLE
Check that anchors are at consistent heights (esp. dot)

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#135] opened 2019-08-10 23:11 UTC
Stephen: write a script to check that anchors are at a consistent y position
- between all masters in the same weight (e.g. A, A slanted)
- between all related letters (dotlessi, dotlessj, dotlessi.italic, dotlessj.italic, etc)

Find a way to check that accents themselves are at a consistent height in related weights.

**Comment by arrowtype** [comment] 2019-11-14 00:59
Closing as a duplicate of https://github.com/arrowtype/recursive/issues/190

**Closed by arrowtype** 2019-11-14 00:59 UTC
Labels: beta 2, priority 1
