### ISSUE TITLE
OpenType features does not get applied in VS Code for Recursive versions > 1.052

### ISSUE THREAD

**Issue by krish-r** [arrowtype/recursive#403] opened 2020-09-12 05:54 UTC
Hi, 

OpenType features does get applied in VS Code from Recursive versions > 1.052.

| | |
| --- | --- |
| OS | Windows 10 1909 |
| Editor | VS Code 1.19.0 |
| Setting | "editor.fontLigatures": "'ss01','ss05','dlig'" |

_Example for - Single-Story 'a' and Simplified 'l'_
---

### **v1.052:** 
**when setting is disabled**
![image](https://user-images.githubusercontent.com/54745129/92988287-c3ee0480-f4e7-11ea-9e97-f22cc1432f31.png)

**when setting is enabled** - _Single-Story 'a' and Simplified 'l'_ are active
![image](https://user-images.githubusercontent.com/54745129/92988298-dd8f4c00-f4e7-11ea-98fe-866a0e803e34.png)

---

### **v1.064:**
 **when setting is disabled** 
![image](https://user-images.githubusercontent.com/54745129/92988371-8047ca80-f4e8-11ea-82e6-fe723b176928.png)

**when setting is enabled** - No change
![image](https://user-images.githubusercontent.com/54745129/92988392-b2592c80-f4e8-11ea-9fd1-4139b58439fc.png)

**Comment by arrowtype** [comment] 2020-09-12 16:36
Hey @krish-r, thanks for filing the issue!

This is the expected & intended behavior, though I should have made it more clear in the readme & documentation. The `Rec Mono` fonts are specifically built to have OpenType features “frozen in” so that they can work in any editor or app, even if it doesn’t have support of feature preferences.

Please see the updated readme section [Font usage in Code Editors](https://github.com/arrowtype/recursive#font-usage-in-code-editors). I’ll close this, but please let me know if you still have any questions about this after reading. Documentation can always be improved, so I’m happy to answer questions and/or update the explanation if you think anything can be made more clear!

**Closed by arrowtype** 2020-09-12 16:36 UTC
