### ISSUE TITLE
Fonts for Code need improved monospace metadata

### ISSUE THREAD

**Issue by javlaks** [arrowtype/recursive#370] opened 2020-08-04 15:33 UTC
**Problem description**
Recursive is not available to select into HeidiSQL

**Expected behavior**
Rec Mono font should be available in the dropdown to select it

**Screenshots**
This is from HeidiSQL
![image](https://user-images.githubusercontent.com/513351/89311711-f4ff2d80-d63b-11ea-815f-54c86c7ed758.png)

This is from Microsoft SQL Server Management Studio
![image](https://user-images.githubusercontent.com/513351/89312482-ebc29080-d63c-11ea-8bcf-b9d9f4020aac.png)

**To Reproduce**
1. Install the font
2. Go to Tools -> Preferences in HeidiSQL menu bar
3. Go to SQL tab
4. Try to find out the font in the dropdown

**Environment**
- OS: Windows 10 v1909
- HeidiSQL: 11.0.0.6067 x64
- Font: 1.053

**Additional context**
Many other fonts are available there. I can see in other editors that Monospaced fonts are in Bold in dropdowns. Recirsive is not appearing in bold in MS SQL Management Studio as you can see in above screenshot.

See this example from same MS SQL Management Studio for other monospaced fonts
![image](https://user-images.githubusercontent.com/513351/89313008-9175ff80-d63d-11ea-9520-5358a2fb82cb.png)

**Comment by arrowtype** [comment] 2020-08-04 18:15
Hi @javlaks, thanks for the detailed report! Sorry you’re having trouble.

Now that these fonts are truly monospaced, I need to add three steps to the code-font process:
1. In the [post](https://docs.microsoft.com/en-us/typography/opentype/spec/post#header) table, `isFixedPitched` flag must be set in the code fonts 
2. In the [OS/2](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#panose) table Panose `bProportion` must be set to `9`, per [this doc](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-doc/6063ca18-7f12-41bf-9e6b-eaaecdc315a0)
3. Also in the OS/2 table, `xAvgCharWidth` should be set to `600` rather than `612` (`612` is an average of glyphs in the "Mono" files which include wide ligatures).

**Comment by arrowtype** [comment] 2020-08-04 21:00
Hi again @javlaks, would you be willing to give one of these families a try?

https://github.com/arrowtype/recursive/tree/450592cf215656baf2728f3580750714622889f0/fonts/rec_mono-for-code

I think they _might_ fix your issue. (Please also do a restart if the issue isn’t immediately fixed on re-install, just to check that it’s not a basic font cache problem.)

**Comment by javlaks** [comment] 2020-08-04 21:53
Hey man, you're great!

They worked and look awesome ♥

![image](https://user-images.githubusercontent.com/513351/89348752-b8025d80-d672-11ea-9479-b339d976b368.png)

![image](https://user-images.githubusercontent.com/513351/89348767-bc2e7b00-d672-11ea-9f97-455ebb812e67.png)

Thank you

**Comment by arrowtype** [comment] 2020-08-04 22:24
Awesome! I'm lucky I recognized the problem from an earlier project. Thanks for taking the time to report that!

**Closed** 2020-08-04 23:00 UTC
Labels: bug
